sudo: required
services:
- docker
language: bash
git:
  depth: 1
env:
  global:
    - LANG=de_DE.UTF-8
script:
- pwd
- docker-compose version
- echo "TRAVIS_BRANCH="$TRAVIS_BRANCH;
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset;
# build images
- cd $TRAVIS_BUILD_DIR/base/build
- docker-compose build
- cd $TRAVIS_BUILD_DIR/sdk/build
- docker-compose build
# push images
- docker images
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker push $DOCKER_USER/alexa_sdk_base:rpi
- docker push $DOCKER_USER/alexa_sdk:rpi
