sudo: required
services:
- docker
language: bash
git:
  depth: 1
env:
  global:
    - LANG=de_DE.UTF-8
script:
- pwd
- docker-compose version
- echo "TRAVIS_BRANCH="$TRAVIS_BRANCH
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# get variables from .env
- cat .env
- export $(cat .env | grep -v ^# | xargs)
- env
# build base image
- cd $TRAVIS_BUILD_DIR/build_base
- docker-compose build
# build image
- cd $TRAVIS_BUILD_DIR/build
- docker-compose build
# push image
- docker images
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker push "$DOCKER_USER"/alexa_sdk:"${BuildEnv}"_"${WakeWordEngine}"_"${SDK_Version}"
- >
  if [ "$BuildEnv" == "ubuntu64" ] ; then
    # exit
    travis_terminate 0;
  fi
- export WakeWordEngine=sensory
# build image
- cd $TRAVIS_BUILD_DIR/build
- docker-compose build
# push image
- docker images
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker push "$DOCKER_USER"/alexa_sdk:"${BuildEnv}"_"${WakeWordEngine}"_"${SDK_Version}"
