sudo: required
services:
- docker
language: bash
git:
  depth: 1
env:
  global:
    - LANG=de_DE.UTF-8
script:
- pwd
- docker-compose version
- echo "TRAVIS_BRANCH="$TRAVIS_BRANCH;
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset;
# build image
- cd $TRAVIS_BUILD_DIR/build
- docker-compose build
# get variables from .env
- export $(cat .env | grep -v ^# | xargs)
- echo "SDK_Version="$SDK_Version;
- echo "KittAI_Version="$KittAI_Version;
- echo "BuildEnv="$BuildEnv;
# push image
- docker images
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker push "$DOCKER_USER"/alexa_sdk:"$BuildEnv"_"$SDK_Version";
