version: '3'

services:
  alexa:
    container_name: al
    image: karsten13/alexa_c:stretch
    ports:
      - 3000:3000
    volumes:
      - ./AlexaClientSDKConfig.json:/srv/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json
#      - ../container/wakeWordAgent/Hilde.pmdl:/srv/alexa-avs-sample-app/samples/wakeWordAgent/ext/resources/alexa.umdl
      - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true
    environment:
      # system params:
      - DISPLAY
      # audio params
      - Audio=3.5mm
    devices:
      - /dev/snd
      - /dev/bus/usb
#    entrypoint: /bin/bash
#    stdin_open: true
#    tty: true      
    restart: always
