version: '3'

services:
  alexa:
    container_name: al
    image: karsten13/alexa_sdk:ubuntu64
    volumes:
      - ./AlexaClientSDKConfig.json:/srv/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json
#      - ./Hilde.pmdl:/srv/sdk-folder/third-party/snowboy/resources/alexa.umdl
    environment:
      # audio params, choose "3.5mm" or "HDMI"
      - Audio=3.5mm
    devices:
      - /dev/snd
      - /dev/bus/usb
    entrypoint:
      - ./entrypoint.sh
#      - DEBUG9
#    entrypoint: /bin/bash
#    stdin_open: true
#    tty: true      
    restart: always

